# Generated by Django 4.2.4 on 2023-08-17 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("MAIN", "0002_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="main_img",
            field=models.ImageField(default="", upload_to="blog"),
            preserve_default=False,
        ),
    ]
