# Generated by Django 4.2.4 on 2023-08-17 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MAIN", "0003_blog_date_blog_description_blog_main_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.DateField(default=datetime.date(2023, 8, 17)),
        ),
    ]
