# Generated by Django 4.2.4 on 2023-08-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MAIN", "0004_alter_blog_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_img", models.BooleanField()),
                ("order", models.IntegerField()),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MAIN.blog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParagraphImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="blog")),
                ("order", models.IntegerField()),
                (
                    "parargraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MAIN.paragraph"
                    ),
                ),
            ],
        ),
    ]
