# Generated by Django 4.2.4 on 2023-08-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MAIN", "0005_paragraph_paragraphimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraph",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
