# Generated by Django 4.2.4 on 2023-08-18 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MAIN", "0006_alter_paragraph_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paragraph",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="paragraphimage",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="blog",
            name="hide",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.DateField(default=datetime.date(2023, 8, 18)),
        ),
    ]
