# Generated by Django 4.2.4 on 2023-08-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MAIN", "0007_alter_paragraph_options_alter_paragraphimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="detail_img",
            field=models.ImageField(
                default=models.ImageField(upload_to="blog"), upload_to="blog"
            ),
        ),
    ]
