# Generated by Django 4.2.4 on 2023-08-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MAIN", "0008_blog_detail_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="detail_img",
            field=models.ImageField(
                blank=True,
                default=models.ImageField(blank=True, upload_to="blog"),
                upload_to="blog",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="main_img",
            field=models.ImageField(blank=True, upload_to="blog"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
