# Generated by Django 4.2.4 on 2023-08-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MAIN", "0009_alter_blog_detail_img_alter_blog_main_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="detail_img",
            field=models.ImageField(blank=True, upload_to="blog"),
        ),
    ]
