# Generated by Django 4.2.4 on 2023-08-19 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MAIN", "0010_alter_blog_detail_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paragraphimage",
            old_name="parargraph",
            new_name="paragraph",
        ),
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.DateField(default=datetime.date(2023, 8, 19)),
        ),
    ]
